### ISSUE TITLE
Specification Version Numbering in the Admin Page needs review

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#57]
<img width="1475" alt="screen shot 2019-01-16 at 15 57 06" src="https://user-images.githubusercontent.com/3616071/51231631-85691500-19a7-11e9-8053-c8eb19a1cbad.png">

The list of Spec versions contains versions outside of known releases. We only have the following official releases:
1.0
1.1
1.2

If there is a need for additional versioning due to internal updates to questions in the web app it should probably take this form:

1.1 
1.1 (Revision 1)

**Comment by shanecoughlan** [comment]
Location: http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/admin.html

**Comment by goneall** [comment]
The git tag refers to the questionnaire version which is the spec version (first 2 digits) followed by a revision number.  The revision number gets incremented when we make a change to the questionnaire within the same spec version (e.g. the recent changes to normalize our reference to "open source").

**Comment by goneall** [comment]
This dropdown list is taken from the tags in the conformance-questionnaire repository.

I like the proposed naming convention, however, it would require re-working some of the back-end logic that maps the questionnaire versions to spec versions.

Since this drop down is only visible to admins (very limited number of users), I recommend we continue with the less clear current version for now and leave this issue open for later development.

**Comment by theopenchainproject** [comment]
Understood. I  think the main priority related to this section (not the specific version number, but the section of the admin page) is the lack of clarity about how to use it. Let's switch our attention to #58, #59 and #60

**Comment by goneall** [comment]
The more I think about it the more I like the idea of using "revision X" to describe the different versions of the questionnaire.

Once we get the localized website up and running, I'll come back to this and work on a fix.

Re-opening the issue for future work.

**Comment by theopenchainproject** [comment]
Sweet. Thanks Gary.
