### ISSUE TITLE
Admin page "Manage Survey Content" needs review - Editing Survey Questions

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Online-Self-Certification-Web-App#59]
<img width="1165" alt="screen shot 2019-01-16 at 15 57 19" src="https://user-images.githubusercontent.com/3616071/51232245-75eacb80-19a9-11e9-8044-6eeb45736866.png">

It is not clear *how* to edit survey questions. I have had no success in trying to do so from the page.

"Update Survey Questions" leads to a blank summary rather than an edit field. It appears to require an "Edit Conformance Questions" button leading to an edit function which then contains "Update Conformance Questions"

Related to #58

**Comment by shanecoughlan** [comment]
Location: http://openchain-env.m6rqmtrixp.us-west-1.elasticbeanstalk.com/admin.html

**Comment by shanecoughlan** [comment]
<img width="1497" alt="screen shot 2019-01-16 at 16 06 18" src="https://user-images.githubusercontent.com/3616071/51232513-599b5e80-19aa-11e9-8d18-0c70216e8f1d.png">

What happens instead is we are lead to this summary page showing no items for submission.

**Comment by goneall** [comment]
Modifying questions are done in the questionnaire github repo.  The process is documented here:  https://github.com/OpenChain-Project/conformance-questionnaire

Note: I would expect that there would only be 2 to 3 users of this feature and they would be trained in the process.

**Comment by theopenchainproject** [comment]
Hi @goneall I can see the process in the repo but I still do not get how this maps to the admin page. It seems this admin page feature is a shortcut to contributing to the questionnaire repo. While it might be useful in a few cases, it offers a different and hard to understand workflow. Personally I think that unless this feature is absolutely needed, we should remove it when we go live, and all editing of the questionnaires should happen solely through the questionnaire repo.

**Comment by goneall** [comment]
@shanecoughlan I agree this is confusing.  Currently, all editing is done through the questionnaire repo and this feature is just to update the web application to whatever was edited.  So the workflow is:

- Update the questionnaire repo with any changes
- Tag the questionnaire repo with a new revision
- Log in as an admin to the web application
- Use this feature to upload the updated questionnaire to the web application

Since this feature is the only way to change the questionnaire, we don't want to remove it.

Once the site is live, I would like to setup a call with anyone volunteering to be an admin to walk through the process.  I think the process is complex enough we need some form of training - perhaps an hour or so on a webconference.

**Comment by theopenchainproject** [comment]
Looks good to me on latest live version!
