### ISSUE TITLE
Admin page: rename incomplete submissions

### ISSUE THREAD

**Issue by theopenchainproject** [OpenChain-Project/Online-Self-Certification-Web-App#77]
<img width="1261" alt="screen shot 2019-01-21 at 16 45 57" src="https://user-images.githubusercontent.com/27284210/51459876-4a972080-1d9d-11e9-99d1-f31b58b191f9.png">

**Comment by goneall** [comment]
@shanecoughlan The "not submitted" technically means the submit button was not pressed or the questionnaire was unsubmitted.  It could be complete or incomplete in terms have having questions answered.  Since "complete" can be interpreted as either having all questions answer or having been completely submitted, I recommend leaving the title as "not submitted" since it is less ambiguous.

**Comment by goneall** [comment]
Fixed with PR #83
