### ISSUE TITLE
All pages: replace all occurrences of "survey" with "questionnaire"

### ISSUE THREAD

**Issue by theopenchainproject** [OpenChain-Project/Online-Self-Certification-Web-App#78]
<img width="1361" alt="screen shot 2019-01-21 at 16 55 53" src="https://user-images.githubusercontent.com/27284210/51459964-8c27cb80-1d9d-11e9-95a2-91e6f26d6d52.png">

Related to #63 and #64

**Comment by goneall** [comment]
Many of these have been fixed in the latest pull request.

I did a search in the HTML and JavaScript files on the pdf_link_added branch and the following remains to be changed:

- admin.js - summaryHtml lines 60-77, 115, 117
- admin.html - lines 129, 139, 143 - update 'survey'
- survey.html - line 51 - reset 'survey' button; line 77 - dialog text for deleting 'survey' answers

**Comment by goneall** [comment]
Resolved in PR #87
